version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../db:/var/lib/postgresql/data
      - ../migrations:/backup
    networks:
      - goat-movie-network

  redis:
    container_name: my-redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ../redis-config/:/tmp/redis.conf
    networks:
      - goat-movie-network

  node-app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_MAX_CONNECTIONS=20
      - DB_IDLE_TIMEOUT=30000
      - DB_CONNECTION_TIMEOUT=2000
      - OMDB_URL=https://www.omdbapi.com
      - API_KEY=2dcb1423
    depends_on:
      - db
      - redis
    working_dir: /app
    networks:
      - goat-movie-network

networks:
  goat-movie-network:
    driver: bridge

